import { Card } from '@mui/material';
import { IRegisterCompany } from 'src/types/register_company';
import RecentOrdersTable from './RecentOrdersTable';

function RecentOrders() {
  const cryptoOrderss: IRegisterCompany[] = [
    {
      id: '1',
      name_company: 'Mcredit - Công Ty Tài Chính TNHH MB Shinsei',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '2',
      name_company: 'Mcredit - Công Ty Tài Chính TNHH MB Shinsei',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '3',
      name_company: 'Mcredit - Công Ty Tài Chính TNHH MB Shinsei',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '4',
      name_company: 'Fiat Deposit',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '5',
      name_company: 'Fiat Deposit',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '6',
      name_company: 'Fiat Deposit',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '7',
      name_company: 'Fiat Deposit',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '8',
      name_company: 'Paypal Withdraw',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '9',
      name_company: 'Fiat Deposit',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
    {
      id: '10',
      name_company: 'Wallet Transfer',
      status: 'completed',
      phone: '0947895039',
      companyField: 'CNTT',
      sourceName: 'Bank Account',
      email: 'sybuivan1429@gmail.com',
      amountCrypto: 34.4565,
      amount: 56787,
      cryptoCurrency: 'ETH',
      currency: '$',
    },
  ];

  return (
    <Card>
      <RecentOrdersTable listCompany={cryptoOrderss} />
    </Card>
  );
}

export default RecentOrders;
